Adds (optional) topic column to changes list
uwolfer/gerrit-intellij-plugin pull request #261
Opened 2017-01-31 11:53 UTC by eekboom

Adds optional "Topic" column to the changes list in the gerrit toolwindow.
Must be enabled via "[ ] Show Topic Column" in gerrit settings, similar to "Changes ID" and "Changed #" columns.

2017-01-31 21:02 UTC, uwolfer requested changes

2017-01-31 21:02 UTC, uwolfer commented on src/main/java/com/urswolfer/intellij/plugin/gerrit/ui/SettingsPanel.form
> -            <clientProperties>
Can you please revert these lines?

2017-01-31 21:02 UTC, uwolfer commented on src/main/java/com/urswolfer/intellij/plugin/gerrit/ui/SettingsPanel.form
> -            <clientProperties>
These as well.

2017-01-31 21:02 UTC, uwolfer commented
Thanks for your PR.

2017-02-01 22:42 UTC, eekboom commented
I tried to amend the commit with a patch that reverts those lines - because I am more used to work with gerrit and patchsets I guess ;-)
That did not work, so now here's a second commit.

BTW: Is it OK if I try similar changes/pull requests for the parent change # and ID?

2017-02-02 16:16 UTC, uwolfer commented
@eekboom: The author email address is different in your two commits. Is this by intention?

When you want to update a PR here, you can amend the first commit and then do a force-push.

2017-02-02 16:32 UTC, eekboom commented
The different e-mails are not really intentional, but a side effect of doing the first on my work notebook and the second commit on my desktop at home.

I shied back from force-pushing because the github docs at https://help.github.com/articles/about-pull-requests/ said not to force push.

I now forced pushed a single commit.

Thanks for your patience!

2017-02-02 16:35 UTC, uwolfer commented
Thanks!

> BTW: Is it OK if I try similar changes/pull requests for the parent change # and ID?

Feel free to do that. Just out of curiosity: what are your usecases for that?

2017-02-02 16:35 UTC, merged

2017-02-02 16:44 UTC, eekboom commented
We are using Jira and have a parent "User Story" for each feature that usually gets multiple sub tasks.
In gerrit we have one change per sub-task and set the topic to the User Story Jira ID.

Multiple changes are dependent on one another, for example a backend change implements a new REST-API and a frontend gerrit change sits on top of that. In this simple scenario it is quite clear that the frontend change is at the top.
When we have more changes in a single story it gets somewhat messy currently.

The latest patch set of the topmost change is automatically deployed in a docker container and as a final step is additionally tested manually. After tests are done all changes of that story are submitted. There it also helps to be able to submit the changes in correct order.

The best solution for us would be a tree view in the changes toolwindow, but I guess that is too complicated to do.

2017-02-02 16:47 UTC, uwolfer commented
Ok, I see.

A tree view is probably quite some work, yes. But not impossible - just see the IntelliJ Git log ;)